spring.application.name=sistema-asistencia

# 1. PUERTO DINÁMICO (Crucial para Render)
server.port=${PORT:8080}

# 2. BASE DE DATOS OCULTA
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. CONFIGURACIÓN DEL BOT Y URL OCULTOS
app.base-url=${APP_URL}
telegram.bot.username=${TELEGRAM_BOT_NAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
# Optimización del Pooler para evitar caídas en Render
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000