spring.application.name=sistema-asistencia

# 1. PUERTO DINÁMICO (Crucial para Render)
server.port=${PORT:8080}

# 2. BASE DE DATOS OCULTA (Mapeada con Render y Supabase)
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Se cambia a 'none' para producción para que Hibernate no intente modificar tablas a través del Pooler (puerto 6543)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 3. CONFIGURACIÓN DEL BOT Y URL OCULTOS
app.base-url=${APP_URL}
telegram.bot.username=${TELEGRAM_BOT_NAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}

# 4. CONFIGURACIÓN DE HIKARI POOL (Evita sobrecargar las conexiones gratuitas)
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000